# NUMPY
* Numerical Python
* Mathematical computation in Python
* Supports arrays and matrices, and math functions for these objects
* Linear ALgebra operations
* Integration with C, C++ and Fortran
* it faster than other built in functions for numerical data analysis

## Arrays
* Array is pack os values, of same type, indexed by a tuple
* Are homogeneous and statics
* Are more efficient in memory usage
* Offer quick implementatinos of math functions
* Faster and more powerfull than lists

In [2]:
import numpy as numpy

In [9]:
# Array criado a partir de uma lista:
vetor1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
print(vetor1)

[0 1 2 3 4 5 6 7 8]


In [6]:
type(vetor1)

numpy.ndarray

In [7]:
# verify the methods available in the object
vetor1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [11]:
# very the number of dimensions available in the array
vetor1.shape

(9,)

## Functions


In [14]:
# arange creates am array range
vetor2 = np.arange (0 , 10, 2)
print(vetor2)

[0 2 4 6 8]


In [23]:
# eye creates an array with the value passed in the diagonal
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
# np.diag creates an array with a specified diagonal
y = np.diag(np.array([1,2,3,4]))
print(y)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


## Matriz
Vector = array unidimensional  
matrix = array bidimensional  
Tensor = array tridimensional

In [28]:
matrix = np.array([[1,2,3],[1,2,3]])
matrix

array([[1, 2, 3],
       [1, 2, 3]])

In [30]:
# creating matrix of ones passing the rows and columns numbers
matrixOnes = np.ones((2,3))
matrixOnes

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
# Matriz out of lists of lists
lista = [[13,81,22], [0, 34, 59], [21, 48, 94]]
matrix2 = np.matrix(lista)
matrix2

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [35]:
np.shape(matrix2)

(3, 3)

In [36]:
np.size(matrix2)

9

In [38]:
# slicing
matrix2[1,1]

34

In [40]:
# change value
matrix2[1,1] = 50
matrix2

matrix([[13, 81, 22],
        [ 0, 50, 59],
        [21, 48, 94]])

In [ ]:
# numpy usually decide data type, if not specified

In [46]:
matriz3 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = int)
matriz3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Basic Statisticst with Numpy

In [48]:
A = np.array([15, 23, 63, 94, 75])

In [49]:
np.mean(A)

54.0

In [50]:
np.std(A)

30.34468652004828

In [51]:
np.sum(A)

270

In [52]:
np.prod(A)

153231750

## More Operations with Numpy

In [53]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [54]:
a[1,1]

1

In [56]:
b = np.arange(30)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [60]:
b[2:9:1]

array([2, 3, 4, 5, 6, 7, 8])

In [61]:
b.min()

0

In [62]:
b.max()

29

In [63]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
# sum to all elements of the array
c + 1.5

array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5])

In [75]:
d = np.concatenate((b,c), axis =0)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,  0,  1,  2,  3,
        4,  5,  6,  7,  8,  9])