# NUMPY
* Numerical Python
* Mathematical computation in Python
* Supports arrays and matrices, and math functions for these objects
* Linear ALgebra operations
* Integration with C, C++ and Fortran
* it faster than other built in functions for numerical data analysis

## Arrays
* Array is pack os values, of same type, indexed by a tuple
* Are homogeneous and statics
* Are more efficient in memory usage
* Offer quick implementatinos of math functions
* Faster and more powerfull than lists

In [2]:
import numpy as numpy

In [9]:
# Array criado a partir de uma lista:
vetor1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
print(vetor1)

[0 1 2 3 4 5 6 7 8]


In [6]:
type(vetor1)

numpy.ndarray

In [7]:
# verify the methods available in the object
vetor1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [11]:
# very the number of dimensions available in the array
vetor1.shape

(9,)

## Functions


In [14]:
# arange creates am array range
vetor2 = np.arange (0 , 10, 2)
print(vetor2)

[0 2 4 6 8]


In [23]:
# eye creates an array with the value passed in the diagonal
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
# np.diag creates an array with a specified diagonal
y = np.diag(np.array([1,2,3,4]))
print(y)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
